# Generated by Django 5.2.5 on 2025-09-13 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='电影类型(e.g. 科幻，动作)', max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='导演/编剧/演员姓名', max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='数据来源网站(e.g. IMDb，豆瓣)', max_length=100, unique=True)),
                ('base_url', models.URLField(help_text='网站主页链接')),
                ('credibility_level', models.IntegerField(default=5, help_text='预设的可信度等级(1-10)，用于加权')),
                ('score_max', models.FloatField(default=10, help_text='该评分体系满分值，用于后续进行归一化处理')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(blank=True, help_text='IMDb ID', max_length=20, null=True, unique=True)),
                ('original_title', models.CharField(db_index=True, default='', help_text='电影的原始语言标题', max_length=200)),
                ('language', models.CharField(default='zh-CN', help_text='语言代码(e.g. zh-CN, en)', max_length=10)),
                ('release_year', models.IntegerField(blank=True, help_text='上映年份', null=True)),
                ('length', models.IntegerField(blank=True, help_text='片长', null=True)),
                ('summary', models.TextField(blank=True, help_text='剧情简介', null=True)),
                ('poster_url', models.URLField(blank=True, help_text='电影海报链接', null=True)),
                ('backdrop_url', models.URLField(blank=True, help_text='电影剧照图链接', null=True)),
                ('genres', models.ManyToManyField(blank=True, to='films_recommender_system.genre')),
                ('actors', models.ManyToManyField(blank=True, related_name='acted_in_movies', to='films_recommender_system.person')),
                ('directors', models.ManyToManyField(blank=True, related_name='directed_movies', to='films_recommender_system.person')),
                ('scriptwriters', models.ManyToManyField(blank=True, related_name='script_write_for_movies', to='films_recommender_system.person')),
            ],
            options={
                'unique_together': {('original_title', 'release_year')},
            },
        ),
        migrations.CreateModel(
            name='MovieTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_text', models.CharField(help_text='标题内容', max_length=200)),
                ('language', models.CharField(default='zh-CN', help_text='语言代码(e.g. zh-CN, en)', max_length=10)),
                ('is_primary', models.BooleanField(default=False, help_text='是否为用于显示的主标题')),
                ('movie', models.ForeignKey(help_text='关联的电影', on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='films_recommender_system.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('recommended_movies', models.ManyToManyField(blank=True, related_name='recommendation', to='films_recommender_system.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, help_text='评论作者', max_length=200, null=True)),
                ('content', models.TextField(help_text='评论内容')),
                ('score', models.FloatField(blank=True, help_text='电影评分', null=True)),
                ('score_max', models.FloatField(default=10, help_text='该评分体系满分值，用于后续进行归一化处理')),
                ('content_date', models.DateTimeField(blank=True, help_text='评论时间', null=True)),
                ('approvals_num', models.IntegerField(blank=True, help_text='该评论被赞同数', null=True)),
                ('movie', models.ForeignKey(help_text='关联的电影', on_delete=django.db.models.deletion.CASCADE, to='films_recommender_system.movie')),
                ('source', models.ForeignKey(help_text='评论来源', on_delete=django.db.models.deletion.CASCADE, to='films_recommender_system.source')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, help_text='用户昵称', max_length=100, null=True)),
                ('signature', models.TextField(blank=True, help_text='个人签名', null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='用户评分(e.g. 1-5)')),
                ('review', models.TextField(help_text='用户评论')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('movie', models.ForeignKey(help_text='评价的电影', on_delete=django.db.models.deletion.CASCADE, to='films_recommender_system.movie')),
                ('user', models.ForeignKey(help_text='评分用户', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'rating')},
            },
        ),
    ]
