# Generated by Django 5.2.5 on 2025-09-02 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_recommender_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='scriptwriter',
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_id',
            field=models.CharField(blank=True, help_text='IMDb ID', max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='original_title',
            field=models.CharField(db_index=True, default='', help_text='电影的原始语言标题', max_length=200),
        ),
        migrations.AddField(
            model_name='movie',
            name='scriptwriters',
            field=models.ManyToManyField(blank=True, related_name='script_write_for_movies', to='films_recommender_system.person'),
        ),
    ]
