# Generated by Django 5.2.5 on 2025-09-14 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_recommender_system', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userreview',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveField(
            model_name='recommendation',
            name='recommended_movies',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='signature',
        ),
        migrations.AddField(
            model_name='recommendation',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='films_recommender_system.movie'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(blank=True, help_text='用户头像', null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='个人简介', null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='profile_background',
            field=models.ImageField(blank=True, help_text='个人中心背景图', null=True, upload_to='backgrounds/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='watchlist',
            field=models.ManyToManyField(blank=True, related_name='watchlisted_by', to='films_recommender_system.movie'),
        ),
        migrations.AlterUniqueTogether(
            name='userreview',
            unique_together={('user', 'movie')},
        ),
        migrations.CreateModel(
            name='BrowsingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_on', models.DateTimeField(auto_now=True, help_text='最近浏览时间')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films_recommender_system.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='browsing_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-viewed_on'],
                'unique_together': {('user', 'movie')},
            },
        ),
    ]
