# Generated by Django 5.2.5 on 2025-09-14 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_recommender_system', '0002_alter_userreview_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userreview',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='userreview',
            name='likes_count',
            field=models.IntegerField(default=0, help_text='该评论被赞同数'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='movie',
            field=models.ForeignKey(help_text='评价的电影', on_delete=django.db.models.deletion.CASCADE, related_name='user_reviews', to='films_recommender_system.movie'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='rating',
            field=models.FloatField(help_text='用户评分 (e.g. 1.0-10.0)'),
        ),
        migrations.AlterField(
            model_name='userreview',
            name='user',
            field=models.ForeignKey(help_text='评分用户', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
