# Generated by Django 5.2.5 on 2025-09-02 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('films_recommender_system', '0002_remove_movie_scriptwriter_movie_imdb_id_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('original_title', 'release_year')},
        ),
    ]
