# Generated by Django 5.2.5 on 2025-09-02 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_recommender_system', '0003_alter_movie_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='score_max',
            field=models.FloatField(default=10, help_text='该评分体系满分值，用于后续进行归一化处理'),
        ),
    ]
