# Generated by Django 5.2.5 on 2025-09-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_recommender_system', '0004_userreview_liked_by_alter_source_score_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='favorite_genres',
            field=models.ManyToManyField(blank=True, help_text='用户喜欢的电影类型', related_name='favorited_by_users', to='films_recommender_system.genre'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='favorite_people',
            field=models.ManyToManyField(blank=True, help_text='用户喜欢的演员/导演', related_name='favorited_by_users', to='films_recommender_system.person'),
        ),
    ]
