# Generated by Django 5.2.5 on 2025-09-16 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_recommender_system', '0005_userprofile_favorite_genres_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='recommended_movie_ids',
            field=models.JSONField(blank=True, help_text='存储由算法生成的推荐电影ID列表', null=True),
        ),
    ]
