# Generated by Django 5.2.5 on 2025-09-16 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_recommender_system', '0006_recommendation_recommended_movie_ids'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='truth_score',
            field=models.FloatField(db_index=True, default=0.0, help_text='根据多源评分计算的全局真值分数'),
        ),
    ]
