# Generated by Django 5.2.5 on 2025-09-16 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('films_recommender_system', '0007_movie_truth_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movietitle',
            name='title_text',
            field=models.CharField(db_index=True, help_text='标题内容', max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='name',
            field=models.CharField(db_index=True, help_text='导演/编剧/演员姓名', max_length=200, unique=True),
        ),
    ]
